species = ["corn", "rattle"]
spots = ["hotspots", "coldspots"]

rule all:
    input: 
        expand("input_tab/{sp}.{spot}.tab.gz", sp=species, spot=spots)

rule generate_input_for_plots:
    input: 
        spot = "spots/{sp}.{spot}.bed",
        rmap = "rmaps/{sp}.rmap.bed.gz",
        cpgi = "features/{sp}.cpgi.bed.gz",
        prdm = "features/{sp}.prdm9.bed.gz",
        gsiz = "gsizes/{sp}.genome"
    output: 
        "input_tab/{sp}.{spot}.tab.gz"
    resources:
        time = 60,
        cpus = 1
    shell: 
        """
        while read line;do
          read scaf start end <<<$(echo "$line" | cut -f1-3);
          region=$(echo $scaf":"$start"-"$end);
          read scaf slop_start slop_end <<<$(echo "$line" | bedtools slop -i - -g {input.gsiz} -b 20000);
          slop_region=$(echo $scaf":"$slop_start"-"$slop_end);
          tabix {input.rmap} $slop_region \
          | bedtools annotate -i - -files {input.cpgi} {input.prdm} {input.spot} \
          | bedtools sort -i - \
          | python ~/bin/add_cl.py -l $region,{wildcards.sp},{wildcards.spot};
        done < {input.spot} | gzip > {output}
        """

